#!/usr/bin/with-contenv sh
## function source start
apk add unzip bash curl --quiet
wget --quiet https://beta.rclone.org/rclone-beta-latest-linux-amd64.zip -O rclone.zip && \
unzip -q rclone.zip && rm rclone.zip && \
mv rclone*/rclone /usr/bin && rm -r rclone*
echo "-> update rclone || done <-"

echo "-> update packages || start <-"
    apk --no-cache update --quiet && apk --no-cache upgrade --quiet && apk --no-cache fix --quiet
    apk del --quiet --clean-protected --no-progress
    rm -rf /var/cache/apk/*
echo "-> update packages || done <-"